---


- name: Converge HAProxy with WAF config
  hosts: test-ag-haproxy-waf
  module_defaults:
    ansible.builtin.setup:
      gather_subset: ['distribution']
  gather_facts: true

  vars:
    no_prompts: true

    haproxy:
      waf: {}

      frontends:
        fe_web:
          bind: ['[::]:80 v4v6']

          security:
            headers: true
            fingerprint_ssl: true
            restrict_methods: true
            allow_only_methods: ['HEAD', 'GET', 'POST']
            # deny_dangerous_methods: true
            block_script_bots: true
            block_bad_crawler_bots: true
            flag_bots: true
            block_script_kiddies: true

          routes:
            be_test:
              domains: ['app.test.ansibleguy.net']

          default_backend: 'be_fallback'

      backends:
        be_test:
          security:
            restrict_methods: true
            allow_only_methods: ['HEAD', 'GET', 'POST']
            # deny_dangerous_methods: true
            block_script_bots: true
            block_bad_crawler_bots: true

          servers:
            - 'srv-1 192.168.10.11:80'
            - 'srv-2 192.168.10.12:80'

        be_fallback:
          lines: 'http-request redirect code 302 location https://github.com/ansibleguy'

  roles:
    - ansibleguy.infra_haproxy
