---

- name: HAProxy | Config | Globals/Defaults
  ansible.builtin.template:
    src: 'templates/etc/haproxy/haproxy.cfg.j2'
    dest: '/etc/haproxy/haproxy.cfg'
    owner: 'root'
    group: 'haproxy'
    mode: 0640
  notify: haproxy-reload

- name: HAProxy | Config | Backends/Frontends/Stats
  ansible.builtin.template:
    src: "templates/etc/haproxy/conf.d/{{ item }}.cfg.j2"
    dest: "/etc/haproxy/conf.d/{{ item }}.cfg"
    owner: 'root'
    group: 'haproxy'
    mode: 0640
  loop:
    - 'backend'
    - 'frontend'
    - 'stats'
  notify: haproxy-reload
