---

- name: HAProxy | Install
  ansible.builtin.import_tasks: debian/install.yml
  tags: [install]

- name: HAProxy | SSL/TLS Certificates
  ansible.builtin.import_tasks: debian/certs.yml
  tags: [ssl, tls, certs, certificates]

# - name: HAProxy | GeoIP
#   ansible.builtin.import_tasks: debian/geoip.yml
#   tags: [geoip]

- name: HAProxy | Config
  ansible.builtin.import_tasks: debian/config.yml
  tags: [config]
